# Generated by Django 5.2.4 on 2025-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('THERAPIST', 'Mental Health Professional'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
