# Generated by Django 5.2.4 on 2025-07-17 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_rename_date_taken_assessment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['name'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['score'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions for taking the assessment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice', verbose_name='Chosen Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.userassessment', verbose_name='User Assessment'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Assessment Name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='assessments.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='assessments.assessment', verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submissions', to='assessments.assessment', verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='AI Feedback'),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='score',
            field=models.IntegerField(verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
