# Generated by Django 5.2.4 on 2025-07-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
