# Generated by Django 5.2.4 on 2025-07-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/')),
                ('link', models.URLField(blank=True, help_text='Alternatively, provide a link to an external resource (e.g., YouTube video, article).', max_length=500, null=True)),
                ('resource_type', models.CharField(choices=[('ARTICLE', 'Article'), ('VIDEO', 'Video'), ('PDF', 'PDF Document'), ('AUDIO', 'Audio File'), ('OTHER', 'Other')], default='ARTICLE', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Resources',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
